# Generated by Django 5.1.7 on 2025-03-16 13:34

import foodrecipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrecipe', '0003_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=foodrecipe.models.recipe_image_file_path),
        ),
    ]
